import { LocationCardDefinition } from "./LocationCard";

export const LOCATION_CARDS: LocationCardDefinition[] = [
  {
    id: "E01",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 3,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E02",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 3,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E03",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 4,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E04",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 4,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E05",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 5,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E06",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 5,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E07",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 6,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E08",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 6,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: "E09",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 7,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "E10",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 7,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "U01",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U02",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U03",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U04",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U05",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U06",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: "U07",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: "U08",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: "U09",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: "U10",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: "R01",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: "R02",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: "R03",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: "R04",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: "R05",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: "R06",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: "R07",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: "R08",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: "R09",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 3,
  },
  {
    id: "R10",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 3,
  },
  {
    id: "S01",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
    ability: 'You immediately defeat all enemies when you enter a new location.'
  },
  {
    id: "S02",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
    ability: 'You immediately hack all doors when you enter a new location.'
  },
  {
    id: "S03",
    name: "Unnamed",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
    ability: 'You immediately clear all hazards when you enter a new location.'
  },
  {
    id: "W01",
    name: "Wasteland",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "W02",
    name: "Wasteland",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: "W03",
    name: "Wasteland",
    enemyCount: 0,
    lockCount: 0,
    hazardCount: 0,
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 0,
  },
];
