import { LocationCardDefinition } from './LocationCard';

export const LOCATION_CARDS: LocationCardDefinition[] = [
  {
    id: '1',
    name: 'Utility Shed',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '2',
    name: 'Remote Terminal',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '3',
    name: 'Vending Machine',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '4',
    name: 'Ad Billboard',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '5',
    name: 'Wrecked Car',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '6',
    name: 'Personal Generator',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '7',
    name: 'Wrecked Truck',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '8',
    name: 'Scrap Pile',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '9',
    name: 'Computer Lab',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '10',
    name: 'Library',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 2,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '11',
    name: 'Commerical Generator',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 2,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '12',
    name: 'Bus Depot',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '13',
    name: 'Repair Bay',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '14',
    name: 'Scrapyard',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 1,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '15',
    name: 'Service Garage',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 1,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '16',
    name: 'Data Bank',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '17',
    name: 'Community Center',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '18',
    name: 'Water Treatment Plant',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 2,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '19',
    name: 'Industrial Generator',
    barriers: {
      enemyCount: 0,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 2,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '20',
    name: 'Transit Control Hub',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '21',
    name: 'Marketplace',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 1,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '22',
    name: 'Union Bank',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 1,
      batteryCount: 1,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '23',
    name: 'Battery Exchange',
    barriers: {
      enemyCount: 0,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 1,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '24',
    name: 'Subway Platform',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 1,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '25',
    name: 'Construction Site',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 2,
      dataCount: 2,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '26',
    name: 'Cooling Site',
    barriers: {
      enemyCount: 0,
      lockCount: 1,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 0,
      dataCount: 2,
      batteryCount: 2,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '27',
    name: 'Parking Garage',
    barriers: {
      enemyCount: 1,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 2,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '28',
    name: 'Records Office',
    barriers: {
      enemyCount: 1,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '29',
    name: 'Fire Station',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 3,
      dataCount: 1,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '30',
    name: 'Courthouse',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 3,
      batteryCount: 1,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '31',
    name: 'Mall Mezzanine',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 3,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '32',
    name: 'Maintenance Tunnel',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 3,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '33',
    name: 'Signal Relay Tower',
    barriers: {
      enemyCount: 2,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 3,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '34',
    name: 'Data Center',
    barriers: {
      enemyCount: 2,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 2,
      batteryCount: 3,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '35',
    name: 'Office Highrise',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 2,
      gearCount: 3,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '36',
    name: 'Drone Center',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 3,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '37',
    name: 'Fiber Hub',
    barriers: {
      enemyCount: 2,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 1,
      dataCount: 2,
      batteryCount: 2,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '38',
    name: 'Tool Depot',
    barriers: {
      enemyCount: 2,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 1,
      batteryCount: 2,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '39',
    name: 'Auto Clinic',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 2,
      dataCount: 0,
      batteryCount: 1,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '40',
    name: 'University',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 2,
      dataCount: 2,
      batteryCount: 0,
      gearCount: 1,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '41',
    name: 'Broadcast Spire',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 3,
    },
    resources: {
      circuitCount: 3,
      dataCount: 3,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '42',
    name: 'Traffic Grid',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 0,
      dataCount: 3,
      batteryCount: 3,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '43',
    name: 'Assembly Line',
    barriers: {
      enemyCount: 3,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 3,
      gearCount: 3,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '44',
    name: 'Loading Bay',
    barriers: {
      enemyCount: 3,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 3,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 3,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '45',
    name: 'Drone Repair Shop',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 2,
      dataCount: 2,
      batteryCount: 2,
      gearCount: 0,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '46',
    name: 'Orbital Dock',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 2,
      batteryCount: 2,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '47',
    name: 'Recycling Center',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 0,
      batteryCount: 2,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '48',
    name: 'Private Vault',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 2,
      dataCount: 2,
      batteryCount: 0,
      gearCount: 2,
    },
    quantumCoreCount: 0,
    quantity: 1,
  },
  {
    id: '49',
    name: 'Quantum Relay',
    barriers: {
      enemyCount: 3,
      lockCount: 2,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '50',
    name: 'Command Spire',
    barriers: {
      enemyCount: 3,
      lockCount: 2,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '51',
    name: 'Energy Nexus',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '52',
    name: 'Arbitration Court',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 3,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '53',
    name: 'Orbital Control Room',
    barriers: {
      enemyCount: 4,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '54',
    name: 'Executive Housing',
    barriers: {
      enemyCount: 4,
      lockCount: 1,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '55',
    name: 'Broadcast Relay',
    barriers: {
      enemyCount: 0,
      lockCount: 4,
      hazardCount: 1,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '56',
    name: 'Overwatch Hub',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 4,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 3,
    quantity: 1,
  },
  {
    id: '57',
    name: 'Deep Archive',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '58',
    name: 'Cryo Facility',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '59',
    name: 'Energy Vault',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '60',
    name: 'Defense Grid',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 2,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '61',
    name: 'Executive Bunker',
    barriers: {
      enemyCount: 3,
      lockCount: 3,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '62',
    name: 'Fusion Lab',
    barriers: {
      enemyCount: 3,
      lockCount: 3,
      hazardCount: 0,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '63',
    name: 'Grid Node Tower',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 3,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
  {
    id: '64',
    name: 'Quantum Reactor',
    barriers: {
      enemyCount: 3,
      lockCount: 0,
      hazardCount: 3,
    },
    resources: {
      circuitCount: 0,
      dataCount: 0,
      batteryCount: 0,
      gearCount: 0,
    },
    quantumCoreCount: 5,
    quantity: 1,
  },
];
