import { LocationCardDefinition } from './LocationCard';

export const LOCATION_CARDS: LocationCardDefinition[] = [
  {
    id: '101',
    name: 'Transmission Tower',
    barriers: ['D'],
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '102',
    name: 'Syndicate Supply Cache',
    barriers: ['E'],
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '103',
    name: 'Dumping Site',
    barriers: ['H'],
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '104',
    name: 'Augmentation Chamber',
    barriers: ['D'],
    energyCount: -1,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: '201',
    name: 'Solar Farm',
    barriers: ['D', 'E'],
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '202',
    name: 'Syndicate Encampment',
    barriers: ['E', 'H'],
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '203',
    name: 'Wrecked Convoy',
    barriers: ['H', 'D'],
    energyCount: 0,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '204',
    name: 'Cybernetic Workshop',
    barriers: ['E', 'D'],
    energyCount: -1,
    upgradeCount: 1,
    resourceCount: 1,
  },
  {
    id: '301',
    name: 'Wind Turbine',
    barriers: ['E', 'H', 'D'],
    energyCount: 3,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '302',
    name: 'Syndicate Outpost',
    barriers: ['H', 'D', 'E'],
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '303',
    name: 'Supply Store',
    barriers: ['D', 'E', 'H'],
    energyCount: 1,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '304',
    name: 'Prototyping Lab',
    barriers: ['E', 'D', 'D'],
    energyCount: 0,
    upgradeCount: 1,
    resourceCount: 0,
  },
  {
    id: '305',
    name: 'Experimental Fabricator',
    barriers: ['E', 'H', 'D'],
    energyCount: -2,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: '401',
    name: 'Energy Station',
    barriers: ['D', 'H', 'D', 'E'],
    energyCount: 4,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '402',
    name: 'Syndicate Warehouse',
    barriers: ['E', 'D', 'E', 'H'],
    energyCount: 3,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '403',
    name: 'Data Center',
    barriers: ['H', 'E', 'H', 'D'],
    energyCount: 2,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '404',
    name: 'Salvage Yard',
    barriers: ['D', 'H', 'E', 'E'],
    energyCount: 0,
    upgradeCount: 1,
    resourceCount: 1,
  },
  {
    id: '501',
    name: 'Power Plant',
    barriers: ['E', 'D', 'E', 'H', 'H'],
    energyCount: 5,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '502',
    name: 'Syndicate Stronghold',
    barriers: ['H', 'E', 'H', 'D', 'D'],
    energyCount: 4,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '503',
    name: 'Trainyard',
    barriers: ['D', 'H', 'D', 'E', 'E'],
    energyCount: 3,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '504',
    name: 'Black Market',
    barriers: ['H', 'H', 'E', 'E', 'E'],
    energyCount: 1,
    upgradeCount: 1,
    resourceCount: 1,
  },
  {
    id: '505',
    name: 'Recycling Center',
    barriers: ['E', 'D', 'H', 'H', 'H'],
    energyCount: 0,
    upgradeCount: 1,
    resourceCount: 2,
  },
  {
    id: '601',
    name: 'Fusion Facility',
    barriers: ['H', 'H', 'E', 'H', 'D', 'D'],
    energyCount: 6,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '602',
    name: 'Syndicate Supply Depot',
    barriers: ['D', 'D', 'H', 'D', 'E', 'E'],
    energyCount: 5,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '603',
    name: 'Shopping Mall',
    barriers: ['E', 'E', 'D', 'E', 'H', 'H'],
    energyCount: 4,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '604',
    name: 'Sealed Vault',
    barriers: ['E', 'D', 'D', 'H', 'H', 'H'],
    energyCount: 1,
    upgradeCount: 1,
    resourceCount: 2,
  },
  {
    id: '605',
    name: 'Cybernetics Lab',
    barriers: ['H', 'H', 'E', 'D', 'D', 'D'],
    energyCount: 0,
    upgradeCount: 2,
    resourceCount: 0,
  },
  {
    id: '701',
    name: 'Energy Nexus',
    barriers: ['D', 'D', 'H', 'D', 'E', 'E', 'D'],
    energyCount: 7,
    upgradeCount: 0,
    resourceCount: 0,
  },
  {
    id: '702',
    name: 'Syndicate Headquarters',
    barriers: ['E', 'E', 'D', 'E', 'H', 'H', 'E'],
    energyCount: 6,
    upgradeCount: 0,
    resourceCount: 1,
  },
  {
    id: '703',
    name: 'Skyscraper',
    barriers: ['H', 'H', 'E', 'H', 'D', 'D', 'H'],
    energyCount: 5,
    upgradeCount: 0,
    resourceCount: 2,
  },
  {
    id: '704',
    name: 'Government Bunker',
    barriers: ['H', 'E', 'E', 'D', 'D', 'D', 'H'],
    energyCount: 2,
    upgradeCount: 1,
    resourceCount: 2,
  },
  {
    id: '705',
    name: 'Reclamation Facility',
    barriers: ['D', 'D', 'H', 'E', 'E', 'E', 'H'],
    energyCount: 0,
    upgradeCount: 2,
    resourceCount: 1,
  },
];
