import { LocationCardDefinition } from './LocationCard';

export const LOCATION_CARDS: LocationCardDefinition[] = [
  {
    id: '1',
    area: 'Blacklight District',
    name: 'Apartment Complex',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 2,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '2',
    area: 'Blacklight District',
    name: 'Parking Garage',
    barriers: {
      enemyCount: 1,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 3,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '3',
    area: 'Blacklight District',
    name: 'Office Building',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 5,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '4',
    area: 'Blacklight District',
    name: 'Storage Center',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 6,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '5',
    area: 'Blacklight District',
    name: 'Marketplace',
    barriers: {
      enemyCount: 3,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 8,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '6',
    area: 'Blacklight District',
    name: 'Skyscraper',
    barriers: {
      enemyCount: 3,
      lockCount: 0,
      hazardCount: 0,
    },
    scrapCount: 9,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '7',
    area: 'Lost Labs',
    name: 'Makerspace',
    barriers: {
      enemyCount: 0,
      lockCount: 1,
      hazardCount: 0,
    },
    scrapCount: 2,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '8',
    area: 'Lost Labs',
    name: 'Robot Workshop',
    barriers: {
      enemyCount: 0,
      lockCount: 1,
      hazardCount: 0,
    },
    scrapCount: 3,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '9',
    area: 'Lost Labs',
    name: 'Science Lab',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 0,
    },
    scrapCount: 5,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '10',
    area: 'Lost Labs',
    name: 'Research Facility',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 0,
    },
    scrapCount: 6,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '11',
    area: 'Lost Labs',
    name: 'R&D Complex',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 0,
    },
    scrapCount: 8,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '12',
    area: 'Lost Labs',
    name: 'Underground Bunker',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 0,
    },
    scrapCount: 9,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '13',
    area: 'Quarantine Zone',
    name: 'Collapsed Building',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 1,
    },
    scrapCount: 2,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '14',
    area: 'Quarantine Zone',
    name: 'Crash Site',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 1,
    },
    scrapCount: 3,
    quantumCoreCount: 0,
    quantity: 4,
  },
  {
    id: '15',
    area: 'Quarantine Zone',
    name: 'Electrical Overload',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 2,
    },
    scrapCount: 5,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '16',
    area: 'Quarantine Zone',
    name: 'Radioactive Area',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 2,
    },
    scrapCount: 6,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '17',
    area: 'Quarantine Zone',
    name: 'Reactor Meltdown',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 3,
    },
    scrapCount: 8,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '18',
    area: 'Quarantine Zone',
    name: 'Quantum Anomaly',
    barriers: {
      enemyCount: 0,
      lockCount: 0,
      hazardCount: 3,
    },
    scrapCount: 9,
    quantumCoreCount: 0,
    quantity: 2,
  },
  {
    id: '19',
    area: 'City Center',
    name: 'Command Vault',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 2,
    },
    scrapCount: 0,
    quantumCoreCount: 8,
    quantity: 2,
  },
  {
    id: '20',
    area: 'City Center',
    name: 'Command Spire',
    barriers: {
      enemyCount: 3,
      lockCount: 3,
      hazardCount: 3,
    },
    scrapCount: 0,
    quantumCoreCount: 12,
    quantity: 1,
  },
  {
    id: '21',
    area: 'City Center',
    name: 'Orbital Relay',
    barriers: {
      enemyCount: 2,
      lockCount: 2,
      hazardCount: 0,
    },
    scrapCount: 0,
    quantumCoreCount: 4,
    quantity: 2,
  },
  {
    id: '22',
    area: 'City Center',
    name: 'Orbital Control Room',
    barriers: {
      enemyCount: 3,
      lockCount: 3,
      hazardCount: 0,
    },
    scrapCount: 0,
    quantumCoreCount: 8,
    quantity: 1,
  },
  {
    id: '23',
    area: 'City Center',
    name: 'Energy Warehouse',
    barriers: {
      enemyCount: 0,
      lockCount: 2,
      hazardCount: 2,
    },
    scrapCount: 0,
    quantumCoreCount: 4,
    quantity: 2,
  },
  {
    id: '24',
    area: 'City Center',
    name: 'Energy Nexus',
    barriers: {
      enemyCount: 0,
      lockCount: 3,
      hazardCount: 3,
    },
    scrapCount: 0,
    quantumCoreCount: 8,
    quantity: 1,
  },
  {
    id: '25',
    area: 'City Center',
    name: 'Executive Office',
    barriers: {
      enemyCount: 2,
      lockCount: 0,
      hazardCount: 2,
    },
    scrapCount: 0,
    quantumCoreCount: 4,
    quantity: 2,
  },
  {
    id: '26',
    area: 'City Center',
    name: 'Executive Suite',
    barriers: {
      enemyCount: 3,
      lockCount: 0,
      hazardCount: 3,
    },
    scrapCount: 0,
    quantumCoreCount: 8,
    quantity: 1,
  },
];
