import { RewardCardDefinition } from './RewardCard';

export const REWARD_CARDS: RewardCardDefinition[] = [
  {
    id: 'R1',
    name: 'Shockwave Grenade',
    description: 'Defeat 1 enemy.',
    quantity: 5,
  },
  {
    id: 'R2',
    name: 'Hunter Drone',
    description: 'Defeat 2 enemies.',
    quantity: 2,
  },
  {
    id: 'R3',
    name: 'Plasma Thrower',
    description: 'Defeat all enemies at a location.',
    quantity: 1,
  },
  {
    id: 'R4',
    name: 'Access Script',
    description: 'Hack 1 door.',
    quantity: 5,
  },
  {
    id: 'R5',
    name: 'Root Kit',
    description: 'Hack 2 doors.',
    quantity: 2,
  },
  {
    id: 'R6',
    name: 'System Virus',
    description: 'Hack all doors at a location.',
    quantity: 1,
  },
  {
    id: 'R7',
    name: 'Hazard Extinguisher',
    description: 'Clear 1 hazard.',
    quantity: 5,
  },
  {
    id: 'R8',
    name: 'Containment Shield',
    description: 'Clear 2 hazards.',
    quantity: 2,
  },
  {
    id: 'R9',
    name: 'Area Sanitizer',
    description: 'Clear all hazards at a location.',
    quantity: 1,
  },
  {
    id: 'R10',
    name: 'Trespass Sensors',
    description: 'When defending, roll twice and take the higher roll.',
    quantity: 2,
  },
  {
    id: 'R11',
    name: 'Combat Enhancer',
    description: 'When attacking, roll twice and take the higher roll.',
    quantity: 2,
  },
  {
    id: 'R12',
    name: 'Explosive Tripwire',
    description: 'When a player attacks you, they are immediately defeated.',
    quantity: 1,
  },
  {
    id: 'R13',
    name: 'Toxic Sandstorm',
    description: 'Play this card immediately. Discard one or more locations.',
    quantity: 1,
  },
  {
    id: 'U1',
    name: 'Hydraulic Actuator',
    description: '+1 Power',
    quantity: 4,
  },
  {
    id: 'U2',
    name: 'Targeting Optics',
    description: '+2 Power',
    quantity: 2,
  },
  {
    id: 'U3',
    name: 'System Coolant',
    description: '+1 Protocol',
    quantity: 4,
  },
  {
    id: 'U4',
    name: 'Quantum Core',
    description: '+2 Protocol',
    quantity: 2,
  },
  {
    id: 'U5',
    name: 'Reinforced Frame',
    description: '+1 Plating',
    quantity: 4,
  },
  {
    id: 'U6',
    name: 'Deflective Shielding',
    description: '+2 Plating',
    quantity: 2,
  },
  {
    id: 'U7',
    name: 'Reactive Matrix',
    description: '+1 Power and +1 Protocol',
    quantity: 3,
  },
  {
    id: 'U8',
    name: 'Core Stabilizer',
    description: '+1 Protocol and +1 Plating',
    quantity: 3,
  },
  {
    id: 'U9',
    name: 'Kinetic Armor',
    description: '+1 Plating and +1 Power',
    quantity: 3,
  },
  {
    id: 'U10',
    name: 'Combat Sequencer',
    description: 'When you defeat an enemy, defeat an adjacent enemy.',
    quantity: 1,
  },
  {
    id: 'U11',
    name: 'Advanced Algorithms',
    description: 'When you hack a door, hack an adjacent door.',
    quantity: 1,
  },
  {
    id: 'U12',
    name: 'Adaptive Lining',
    description: 'When you clear a hazard, clear an adjacent hazard.',
    quantity: 1,
  },
];
