import { SynCityCard } from "./Card";

export const SYN_CITY_CARDS: SynCityCard[] = [
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "power",
    attributeCost: 1,
    name: "Strike",
    description: "Attack an enemy at **CLOSE** range for **2 damage**.",
  },
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "precision",
    attributeCost: 1,
    name: "Shoot",
    description: "Attack an enemy at **FAR** range for **2 damage**.",
  },
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "protocol",
    attributeCost: 1,
    name: "Hack",
    description: "Hack an enemy at **CLOSE/FAR** range for **2 damage**.",
  },
  {
    actionType: "condition",
    actionCost: 1,
    attributeKey: "persona",
    attributeCost: 1,
    name: "Support",
    description: "When an ally attacks, add **2 damage**.",
  },
  {
    actionType: "condition",
    actionCost: 1,
    attributeKey: "plating",
    attributeCost: 1,
    name: "Deflect",
    description: "When attacked, negate **2 damage**.",
  },
  {
    actionType: "condition",
    actionCost: 0,
    attributeKey: "propulsion",
    attributeCost: 1,
    name: "Move",
    description: "Move to an adjacent sector.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "power",
    attributeCost: 2,
    name: "Steel Knuckles",
    description: "Your melee attacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "precision",
    attributeCost: 2,
    name: "Targeting Optics",
    description: "Your ranged attacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "protocol",
    attributeCost: 2,
    name: "Corrupted Payload",
    description: "Your hacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "persona",
    attributeCost: 2,
    name: "Inspiration",
    description: "Allies at **CLOSE** range deal **+1 damage** on attacks.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "plating",
    attributeCost: 2,
    name: "Reinforced Frame",
    description: "When attacked, negate **1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "propulsion",
    attributeCost: 2,
    name: "Hydraulic Shocks",
    description: "When you move sectors, draw a card.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "power",
    attributeCost: 2,
    name: "Locked in",
    description: "If you dealt a melee attack this turn, your following melee attacks deal **+2 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "precision",
    attributeCost: 2,
    name: "Zeroed In",
    description: "If you dealt a ranged attack this turn, your following ranged attacks deal **+2 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "protocol",
    attributeCost: 2,
    name: "Energy Siphon",
    description: "When hacked, steal **1 health** from the attacker.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "persona",
    attributeCost: 2,
    name: "Distracting Presence",
    description: "Enemy ranged attacks deal **-1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "plating",
    attributeCost: 2,
    name: "Electroshock Plating",
    description: "When attacked, deal **2 damage** back on the attacker.",
  },
  {
    actionType: "effect",
    actionCost: 2,
    attributeKey: "propulsion",
    attributeCost: 2,
    name: "Sonic Surprise",
    description: "When you move sectors, your next attack deals **+4** damage.",
  },
];
