import { SynCityCard } from './Card';

export const SYN_CITY_CARDS: SynCityCard[] = [
  {
    actionType: 'activate',
    actionCost: 0,
    attributeKey: 'propulsion',
    attributeCost: 0,
    name: 'Bipedal Skeleton',
    description: 'Move up to 5 meters.',
    visible: true,
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'power',
    attributeCost: 1,
    name: 'Steel Knuckles',
    description: 'Attack an enemy within **REACH**. Deal **2 damage**.',
    visible: true,
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'precision',
    attributeCost: 1,
    name: 'Steel Knives',
    description: 'Attack an enemy at **CLOSE** range. Deal **1 damage**.',
    visible: true,
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'protocol',
    attributeCost: 1,
    name: 'Short Circuit',
    description: 'Hack an enemy from **LONG** range. Deal **1 damage**.',
    visible: true,
  },
  {
    actionType: 'condition',
    actionCost: 1,
    attributeKey: 'persona',
    attributeCost: 1,
    name: 'Smooth Operation',
    description:
      '*Activate to set.* While set, add **2 damage** to the next ally attack at **CLOSE** range.',
    visible: true,
  },
  {
    actionType: 'condition',
    actionCost: 1,
    attributeKey: 'plating',
    attributeCost: 1,
    name: 'Deflective Armor',
    description:
      '*Activate to set.* While set, negate **2 damage** from the next attack against you.',
    visible: true,
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'propulsion',
    attributeCost: 1,
    name: 'Powered Treads',
    description: 'Move up to 10 meters.',
    visible: true,
  },
  {
    actionType: 'effect',
    attributeKey: 'power',
    attributeCost: 1,
    name: 'Hydraulic Actuators',
    description: 'Your melee attacks deal **+1 damage**.',
    visible: true,
  },
  {
    actionType: 'effect',
    attributeKey: 'precision',
    attributeCost: 1,
    name: 'Targeting Optics',
    description: 'Your ranged attacks deal **+1 damage**.',
    visible: true,
  },
  {
    actionType: 'effect',
    attributeKey: 'protocol',
    attributeCost: 1,
    name: 'Corrupted Payload',
    description: 'Your hacks deal **+1 damage**.',
    visible: true,
  },
  {
    actionType: 'effect',
    attributeKey: 'persona',
    attributeCost: 1,
    name: 'Inspiring Presence',
    description: 'Allies at **CLOSE** range deal **+1 damage** on attacks.',
    visible: true,
  },
  {
    actionType: 'effect',
    attributeKey: 'plating',
    attributeCost: 1,
    name: 'Reinforced Frame',
    description: 'When attacked, negate **1 damage**.',
    visible: true
  },
  {
    actionType: 'effect',
    attributeKey: 'propulsion',
    attributeCost: 1,
    name: 'Regenerative Brakes',
    description: 'If you move this turn, gain **1 synergy**.',
    visible: true
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'power',
    attributeCost: 1,
    name: 'Impact Gauntlet',
    description: 'Attack an enemy within **REACH**. Deal **4 damage**.',
    visible: true,
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'precision',
    attributeCost: 1,
    name: 'Razor Shurikens',
    description: 'Attack an enemy at **CLOSE** range. Deal **2 damage**.',
    visible: true,
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'power',
    attributeCost: 2,
    name: 'Locked in',
    description:
      'If you dealt a melee attack this turn, your following melee attacks deal **+2 damage**.',
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'precision',
    attributeCost: 2,
    name: 'Zeroed In',
    description:
      'If you dealt a ranged attack this turn, your following ranged attacks deal **+2 damage**.',
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'protocol',
    attributeCost: 2,
    name: 'Energy Siphon',
    description: 'When hacked, steal **2 health** from the attacker.',
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'persona',
    attributeCost: 2,
    name: 'Distracting Presence',
    description: 'Enemy ranged attacks deal **-1 damage**.',
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'plating',
    attributeCost: 2,
    name: 'Electroshock Plating',
    description: 'When attacked... deal **2 damage** back on the attacker.',
  },
  {
    actionType: 'effect',
    actionCost: 2,
    attributeKey: 'propulsion',
    attributeCost: 2,
    name: 'Sonic Surprise',
    description: 'When you move sectors, your next attack deals **+4** damage.',
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'power',
    attributeCost: 8,
    name: 'Forced Relocation',
    description:
      'Grab and throw an enemy at **CLOSE** range into an adjacent sector of your choice. That enemy takes **8 damage**.',
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'precision',
    attributeCost: 8,
    name: 'Cryogenic Aim',
    description: 'Until the start of your next turn, your ranged attacks deal double damage.',
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'protocol',
    attributeCost: 8,
    name: 'System Reboot',
    description:
      'Hack an enemy at **CLOSE/FAR** range. That enemy enters sleep mode until the start of your next turn.',
  },
  {
    actionType: 'activate',
    actionCost: 1,
    attributeKey: 'persona',
    attributeCost: 8,
    name: 'Recycling',
    description:
      'Siphon the synergy from a shutdown enemy in your sector. You and your allies start their next turn with **+1 synergy**.',
  },
  {
    actionType: 'condition',
    actionCost: 1,
    attributeKey: 'plating',
    attributeCost: 8,
    name: 'Hazmat Suit',
    description: 'When attacked, negate all damage. *Discard at the start of your next turn.*',
  },
  {
    actionType: 'condition',
    actionCost: 1,
    attributeKey: 'propulsion',
    attributeCost: 8,
    name: 'Backblast',
    description:
      'When you move into a new sector, all enemies in it take **2 damage**. *Discard at the start of your next turn.*',
  },
];
