import { SynCityCard } from "./Card";

export const SYN_CITY_CARDS: SynCityCard[] = [
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "power",
    attributeCost: 1,
    name: "Strike",
    description: "Deal **2 damage** at **CLOSE** range.",
  },
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "precision",
    attributeCost: 1,
    name: "Shoot",
    description: "Deal **2 damage** at **FAR** range.",
  },
  {
    actionType: "activate",
    actionCost: 1,
    attributeKey: "protocol",
    attributeCost: 1,
    name: "Hack",
    description: "Deal **2 damage** at **CLOSE/FAR** range.",
  },
  {
    actionType: "condition",
    actionCost: 1,
    attributeKey: "persona",
    attributeCost: 1,
    name: "Support",
    description: "When an ally attacks, add **2 damage**.",
  },
  {
    actionType: "condition",
    actionCost: 1,
    attributeKey: "plating",
    attributeCost: 1,
    name: "Deflect",
    description: "When attacked, negate **2 damage**.",
  },
  {
    actionType: "condition",
    actionCost: 0,
    attributeKey: "propulsion",
    attributeCost: 1,
    name: "Move",
    description: "Move to an adjacent sector.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "power",
    attributeCost: 2,
    name: "Steel Knuckles",
    description: "All **Power** attacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "precision",
    attributeCost: 2,
    name: "Targeting Optics",
    description: "All **Precision** attacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "protocol",
    attributeCost: 2,
    name: "Corrupted Payload",
    description: "All **Protocol** attacks deal **+1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "persona",
    attributeCost: 2,
    name: "Inspiration",
    description: "Allies at **CLOSE** range deal **+1 damage** on all attacks.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "plating",
    attributeCost: 2,
    name: "Reinforced Frame",
    description: "When attacked, negate **1 damage**.",
  },
  {
    actionType: "effect",
    actionCost: 1,
    attributeKey: "propulsion",
    attributeCost: 2,
    name: "Hydraulic Shocks",
    description: "When you move sectors, draw a card.",
  },
];
